### ISSUE TITLE
3500hs watched in a single day

### ISSUE THREAD

**Issue by EmmanuelMess** [RakSrinaNa/YTTracker#11]
Something might have broken that day, and now the chart scale makes no sense, as it goes from 00:00:00 to 3500:00:00 on the Y axis.

![Captura de pantalla de 2019-10-07 13-50-40](https://user-images.githubusercontent.com/10991116/66331680-78130280-e909-11e9-9ce2-74e897b0d273.png)

On firefox.

**Comment by RakSrinaNa** [comment]
I'll try to add an axis break instead in the next version and you'll tell me if it's a working solution to your problem

**Comment by RakSrinaNa** [comment]
Not sure if it'd be a good solution actually. The data isn't altered and still allow to see the evolution of the "normal" values. But the way it is displayed may confuse people even more. (And it breaks the y duration axis 😢 )

![firefox_F90aJHvPfi](https://user-images.githubusercontent.com/1688389/66395622-34d39500-e9d8-11e9-8d73-dcb8dffd831a.png)
![firefox_dNoHKJr6id](https://user-images.githubusercontent.com/1688389/66395631-37ce8580-e9d8-11e9-812d-1c9d324e12ca.png)

And as you said, something probably broke that day and this value is just not relevant at all.

So as a first step I'll try to go another way and just take advantage of the vertical scrollbar on the right to make it zoom to a more coherent view (like from 0h to 48h). Like that you still can go view that super weird value so you know where the super high `All data - Opened time` comes from.

Maybe after I'll add a way to take down these extreme values to more reasonable ones so that people can avoid having all destroyed data

**Comment by RakSrinaNa** [comment]
I sent version 2.1.2 to the stores. At some point you should get the update.

This will add a new section under the chart that will allow you to edit these very high values (more than 2 days). Probably not the perfect solution but this should at least help you removing these values that pollute your stats and chart.
