### ISSUE TITLE
"Open chart" button not working

### ISSUE THREAD

**Issue by EmmanuelMess** [RakSrinaNa/YTTracker#12]
"Back to chart" on settings work, but not "Open chart" in main view.

Firefox quantum.

**Comment by RakSrinaNa** [comment]
The main view is the window that you open through the little logo on the top right corner right?

What version of the extension and Firefox (To see that go into the menu on the top right > Help > About Firefox) do you use?

**Comment by EmmanuelMess** [comment]
69.0.1 (64-bit)

**Comment by RakSrinaNa** [comment]
Didn't manage to reproduce it on this setup:
- Windows 10 (64-bits)
- Firefox 69.0.1 (64-bit)
- YouTube Tracker 2.1.2

**Comment by EmmanuelMess** [comment]
@RakSrinaNa  Ubuntu 18.04 with Gnome, sorry, I thought it wouldn't make a difference.

**Comment by RakSrinaNa** [comment]
Tried with:
- Ubuntu 18.04.3 (64-bits)
- Firefox 69.0.2 (64-bit)
- YouTube Tracker 2.1.2
and couldn't reproduce again.

I'll push another update (2.1.3) later modifying a bit how the tabs are opened. Tell me if it fix your problem.

Else should try it this extension alone in a new profile to see if the problem persists or if it's due to anoher extension blocking it? Like an adblocker maybe.

**Comment by EmmanuelMess** [comment]
@RakSrinaNa PopUpBlockerUltimate, forgot I installed that one... Sorry.

**Comment by RakSrinaNa** [comment]
It's fine no worries.
